### ISSUE TITLE
Main event loops terminate when connection errors are received

### ISSUE THREAD

**Issue by mattsaxon** [beveradb/pysonofflan#45]
* pySonoffLAN version: latest
* Python version: 3.7
* Operating System: HASSOS

### Description
Main event loops terminate when connection errors are received

### What I Did
This issues is the root cause of the sonoff-lan-mode repo [issue 56](https://github.com/beveradb/sonoff-lan-mode-homeassistant/issues/56)

I have a draft PR which fixes the issue I've experienced for your review.

**Comment by beveradb** [comment]
Thanks again for this, and sorry for my slow responses!
I've looked through, tested and merged this evening, and will be releasing a new version of `pysonofflan` shortly to allow updating the hass component.

**Comment by beveradb** [comment]
That's version `0.3.0` released to PyPI with your changes merged in - thanks again!
