### ISSUE TITLE
pysonofflan discover: Caught Exception: can't start new thread

### ISSUE THREAD

**Issue by djDuff** [beveradb/pysonofflan#49]
* pySonoffLAN version: 0.2.1
* Python version: Python 3.5.3
* Operating System: Raspbian GNU/Linux 9.9 (stretch)

### Description
After fresh install, I get an exception: Caught Exception: can't start new thread
Any ideas howto troubleshoot?

### What I Did
pip3 install pysonofflan 
pi@dj-raspberry3b:~ $ pysonofflan discover
2019-05-01 19:49:38,804 - info: Attempting to discover Sonoff LAN Mode devices on the local network, please wait...
2019-05-01 19:49:38,954 - error: Caught Exception: can't start new thread

**Comment by beveradb** [comment]
No idea what would cause this - are you running in an environment which doesn't allow threading or something?

Additionally, please can you try with the latest version (`0.3.0`) which has just been released? The async code has been recently improved.

**Comment by fire-fly** [comment]
Hi
I installed pysonofflan 0.3.0 on ubuntu 18.04
Python version
/usr/bin/python -> /usr/bin/python3.6
$pip install pysonofflan
$pysonofflan discovery
bash: /usr/lib/command-not-found: /usr/bin/python3: bad interpreter: No such file or directory

Next
add /usr/bin/python3 -> /usr/bin/python3.6
$pysonofflan discovery
pysonofflan: command not found

Next
$unlink /usr/bin/python3.6
$pip3 install pysonofflan
$pysonofflan discovery
pysonofflan: command not found

**Comment by mattsaxon** [comment]
Fixed by PR https://github.com/beveradb/pysonofflan/pull/95
