### ISSUE TITLE
3.0.x firmware support

### ISSUE THREAD

**Issue by mattsaxon** [beveradb/pysonofflan#54]
* pySonoffLAN version: latest (my PR)
* Python version: 3.7
* Operating System: Hassio (also verified hang on Windows/WebSockets7 via CLI.py)

### Description

Upgrade to latest firmware to see if it still work

### What I Did

After upgrading firmware, restarted HA.

Result is a failure (hang for 5 minutes) at self.websocket = await websockets.connect( in pysonofflan/client.py)

```
2019-05-03 12:28:23 DEBUG (MainThread) [pysonofflan.client] __init__()
2019-05-03 12:28:23 DEBUG (MainThread) [pysonofflan.client] __init__() exiting

```
Then 5 mins later

```
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] connection_lost()
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] client - event = connection_lost(None)
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] client - state = CLOSED
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] client x code = 1006, reason = [no reason]
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] abort_keepalive_pings()
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] close_connection()
2019-05-03 12:33:24 DEBUG (MainThread) [pysonofflan.client] super.close_connection() finished
2019-05-03 12:33:24 ERROR (MainThread) [homeassistant.components.switch.sonoff_lan_mode] SonoffLANModeClient connection failed: Malformed HTTP message
2019-05-03 12:33:24 WARNING (MainThread) [homeassistant.components.switch.sonoff_lan_mode] Unable to connect: Malformed HTTP message
```

The LAN Mode functions well via the eWeLink app.

**Comment by mattsaxon** [comment]
Here's the new startup packet
```

E..e..@.@......q...........     ..EfP...4...POST /zeroconf/switch HTTP/1.1
Host: 192.168.0.227:8081
Content-Type: application/json;charset=UTF-8
User-Agent: ewelinkDemo/1 CFNetwork/978.0.7 Darwin/18.5.0
Connection: keep-alive
Accept: application/json
Accept-Language: en-gb
Content-Length: 205
Accept-Encoding: gzip, deflate
Cache-Control: no-store

```

...... significantly different from firmware 2.6!

**Comment by ivanfmartinez** [comment]
Maybe its using this protocol : 

https://github.com/itead/Sonoff_Devices_DIY_Tools/blob/master/other/SONOFF%20DIY%20MODE%20Protocol%20Doc.pdf

**Comment by mattsaxon** [comment]
Yes, it looks like it may be Also I note the new protocol is not WebSockets, but HTTP REST.

**Comment by mattsaxon** [comment]
I've verified that the new protocol needs the encryption, but is susceptible to replay attacks.

The protocol for the encryption does seem to be documented in the above specification, so I may try to replicate that. However the encryption is dependant on the selfApikey and I'm not sure how to obtain that at this point without sniffing the LAN

**Comment by mattsaxon** [comment]
Thinking on the selfApikey, its likely to be found at registation as per this older API hack doc https://blog.ipsumdomus.com/sonoff-switch-complete-hack-without-firmware-upgrade-1b2d6632c01

I think for now, I will try to see if I can recreate the encryption algo in Python code and take the api key from the LAN sniff. If I can do that, this should move this forward.

**Comment by mattsaxon** [comment]
I've validated that the protocol in the doc is implemented and created a python implementation using PyCryptodome. The API key can be found using the original method still as per the above doc.

`HTTP GET http://10.10.7.1/device` (on the “ITEAD-10000” network)

It can also be sniffed from the LAN after it connects back the real wifi network during paring.

which provides the API key in the following, slightly revised, format
`{"deviceid":"xxxxxxxxxxxx","apikey":"xxxxxxxxxxxxxxxx","accept":"post","chipid":"xxxxxxxxxxx"}`

This API key obtained this was is (happily, from a security point of view of not from a hackers) different from the selfApiKey.

**Comment by mattsaxon** [comment]
I'm have been making some progress on this, but I'm going to hold off for now as I've noted there are a number of commits being made here today https://github.com/itead/Sonoff_Devices_DIY_Tools/tree/master/code.

Looks like we may get a reference implementation from ITead! 

Although it won't execute due to a missing dependency at this exact moment. I'm going to follow this repo and see what unfolds

**Comment by mattsaxon** [comment]
Dependency is now updated and the script and UI at the ITEAD repo execute. However it doesn't fund any device on my LAN. I suspect this is because the ITEAD too doesn't support encryption at the moment (maybe some of the new R3/DIY devices ship with encryption turned off?)

**Comment by mattsaxon** [comment]
Also I note that the use the Zeroconf implementation in use doesn't support notification of updates to the TXT record (needed so the client can get notifcation of the physical switch on the device being used), so the implementation by ITEAD is a polling implementation. I'm preparing an update to the Zeroconf implementation to support notifications at the moment.

**Comment by mattsaxon** [comment]
Zeroconf PR has been accepted and I've verified that the ITEAD implementation broadly works once I've added the encrpytion/decryption routines (see here in my fork https://github.com/mattsaxon/Sonoff_Devices_DIY_Tools)

However looking at the ITEAD plans to enhance (no committments), I think for now I'll probably base a V3 firmware on this repo's code, or at least the interface, that way the HA component (also from @beveradb) will work (largely) unchanged.

I'll report back when I get a chance to work on this or have some progress to report.

**Comment by mattsaxon** [comment]
I've been making good progress with the code, but have some bad news to report on the new devices stability! I 'trashed' 2 SonOff devices, one S26 and one T1 UK. I thought the first device was faulty as it has a dodgy button, but on the second device, it must be something I've done.

My code can discover the devices and obtain the status without issues, but when its send operating instructions (on/off), the device then starts to behave badly, dropping off wifi and having to be re-paired.

This failure is a hard failure, I can't seem to recover the device back to a stable situation even using the stock eWeLink app.

As you can probably expect, I'm loathed to try a 3rd at this stage!

**Comment by mattsaxon** [comment]
I have a first working version in a [branch of my forked repo](https://github.com/mattsaxon/pysonofflan/tree/V3-Firmware) if anyone want to take a look, its very rough and ready however (i've only tested the cli for 'state', 'listen', 'on', 'off')

My next decision is how to package these changes... i.e. do we need a single component that works with both 2.x and 3.x firmware? Is the code complexity worthwhile or shall we leave 2.x behind?

My initial inclination is to run the two branches as separate side-by-side components (separate namespaces) such that the complexity is left behind once all devices are upgraded to 3.x, but would welcome feedback on the subject.

**Comment by ivanfmartinez** [comment]
I have some devices in 2.x and some in 3.x.

As an user I will preffer a single codebase that will detect the device version and use the specific classes/protocols to talk with the devices.

**Comment by mattsaxon** [comment]
I appreciate that is a good place to get to, but there are some complexities to achieve that which mean this can’t, at present be invisible to the user.

The main driver for that is that for 3.x firmware (non DIY devices) encryption is required. This means that users will have to ‘sniff’ the api key. The sheer complexity of doing this means that the choice will be highly visible to a user, at least until ITEAD exposes the APi key in the eWeLink app.

Because of this complexity and the resultant configuration, I think having 2 components is not too much additional complexity for the user. The benefit is that the code will be much cleaner and hence more reliable.

**Comment by mattsaxon** [comment]
What the reason you have a mix for 2.x and 3.x? Is that likely to continue?

**Comment by mattsaxon** [comment]
Here's what I think a side by side config would look like;

- platform: sonoff_lan_mode
  name: Old Device
  host: ESP_xxxxxx

- platform: sonoff_lan_mode_r3
  name: New Device 
  deviceid: 1000xxxxxx
  apikey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  
Note, I expect to move to using deviceid to identity the specific device rather than hostname or IP address. This is because there will no longer be a need to filter the ip address in your router as LAN mode works without internet blocking in R3 firmware. Also the deviceid is visible in the eWeLink app, so it easier for the user to find compared to the hostname. If ITEAD would expose the API key in the app that would be useful, I'll probably post a request for this here once I get a bit further with this prototype https://support.itead.cc/support/discussions/forums/1000228728

**Comment by ivanfmartinez** [comment]
> What's the reason that you have a mix of 2.x and 3.x? Is that likely to continue?

Currently I have two devices that are using 3.x and seven using 2.x.

Using the ewelink and iftt the 3.x are not realiable as 2.x . Probably I will wait more before doing the upgrade and is easier to use a single code for all devices. Even with different config.

In my case all sonoff devices have fixed IP addresses defined in my DHCP server, if possible I preffer to have also the host as an optional parameter to make connection faster because will not have to detect the ip address.

Also I prefer to have the all the devices that does not have to access internet blocked in my firewall.

**Comment by mattsaxon** [comment]
@ivanfmartinez, thanks for your thoughts.

@beveradb, how do you feel about a single component for sonoff_lan_mode and a split pysonofflan and pysonofflan3 components? This will make it simple for user install, but still split the code base allowing easier maintenance. The alternative option, which i now realise needs a fair bit of extra refactoring is to have 2 client module and drive down all web sockets specific  interactions into client.py. Although cleaner, this second option I think is much more work.

**Comment by mattsaxon** [comment]
The code committed in my forked repos (I have a branch called V3-Firmware in both my forked pysonofflan and sonoff_lan_mode repos)  now works in side by side mode as described above and I'm testing with a mix of devices (around 4 x v3.0.1, around 10 v2.6.x). My plan is to run them like this for a few days and look to work on any stability issues I find).

It's still rough and ready, but if anyone else wants to do some testing and report back that would be helpful. If anyone is game, I'll describe my setup to them and how to install... this is not nicely packaged yet!

Once I've passed that step successfully, I'll start tidying and packaging the code better.

**Comment by hdjweb** [comment]
If you want I want to help you I have sonoff basic sonoff pow and sonoff 4ch pro so I can give you what you want but you must explain what will I do because I am not a programmer as you

**Comment by mattsaxon** [comment]
Thanks for the offer. I’m pretty certain. The 4ch won’t work as I think it is shown as a single device in EWeLink. The basic and pows should probably work if you are on firmware 3. How comfortable are you with non development, but technical tasks such as sniffing lan traffic?

**Comment by mattsaxon** [comment]
First draft PR now submitted for initial review https://github.com/beveradb/pysonofflan/pull/76

**Comment by barbieri** [comment]
@mattsaxon I tried your branch V3-Firmware, but it's not working... seems I'm getting the wrong API key:

```
$ pysonofflan --host $DEVICE_IP --api_key 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' --device_id $DEVICE_ID state
...
2019-08-03 19:23:10,900 - error: Error decrypting for device 1000763d87: Padding is incorrect., probably wrong API key
```

I got the API key using Charles Proxy with SSL turned on in my smartphone while using eWeLink, for instance I turned my lights on/off, the POST payload contained `selfApiKey` and it looks like: `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`. I've tried to the decrypt myself using both the MD5 of this key (with and without `-`) as well as `bytes.fromhex()` (since it's 16 bytes, the block size).

Let me know if this key should be acquired elsewhere.

**Comment by mattsaxon** [comment]
Myself and @beveradb have decided to fix this is a different forked repo for the moment as firmware 3.x is so different in behaviour, repo is here https://github.com/mattsaxon/pysonofflan

**Comment by mattsaxon** [comment]
The selfApiKey is not the same as the api_key. See here for an explanation of how to find the api-key https://github.com/mattsaxon/sonoff-lan-mode-homeassistant

Would you be able to post issues with my branch in the respective repository please?

**Comment by barbieri** [comment]
> The selfApiKey is not the same as the api_key. See here for an explanation of how to find the api-key https://github.com/mattsaxon/sonoff-lan-mode-homeassistant

I'll check during the week, thanks for noting that `selfApiKey` is not the actual `api_key` (maybe make it more clear in the docs/message?). I'll also see if I can help to automate that part as well (after I get the manual steps to work).

> Would you be able to post issues with my branch in the respective repository please?

Will do.

**Comment by barbieri** [comment]
@beveradb maybe delete the `V3-Firmware` branch in this repository? Or sync it with @mattsaxon 's?

**Comment by mattsaxon** [comment]
> maybe make it more clear in the docs/message

Done
